# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170909_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='userguardian',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='userguardian',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGuardian',
        ),
    ]
