# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170909_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
